random_seed: 0
work_dir: /work/robinpark
root_dir: ${work_dir}/AutoLabelClassifier
raw_dicom_folder: ${work_dir}/data-apr23/PID010A
clean_path: ${work_dir}/PID010A_clean
updated_clean_path: ${work_dir}/NCIMI_clean
unpaired_reports: /work/rhydian/ProcessedSpinalMRIReports/
model_weights_save_path: /work/robinpark/from_nfs2/models
osc_reports: ${work_dir}/AutoLabelClassifier/data/osclmric_reports

patient_metadata: ${clean_path}/patient_metadata.csv
conclusion_training_data: ${clean_path}/segmented_unpaired_reports_sum_no_len_limit.csv

train_labeled_data: ${updated_clean_path}/ncimi_sampled_test_set_labeled.csv
labeled_data: ${updated_clean_path}/ncimi_sampled_train_set_labeled.csv
no_hist_labeled_data: ${updated_clean_path}/ncimi_sampled_train_set_labeled.csv 
full_ncimi_data: ${updated_clean_path}/unique_reports.csv
seg_full_ncimi_data: ${updated_clean_path}/segmented_unique_reports.csv

osc_train_data: ${osc_reports}/osclmric_reports_labeled_train.csv
osc_test_data: ${osc_reports}/osclmric_reports_labeled_test.csv

ce_train_data: ${osc_reports}/manually_labeled_cauda_equina_train.csv
ce_test_data: ${osc_reports}/manually_labeled_cauda_equina_test.csv

hern_train_data: ${osc_reports}/herniation_reports_labeled_train.csv
hern_test_data: ${osc_reports}/herniation_reports_labeled_test.csv

llm_results_path: ${root_dir}/data/report_labels
inf_labels: ${work_dir}/AutoLabelClassifier/data/report_labels

ntp_model: /scratch/shared/beegfs/robinpark/zephyr-uprep-conclusion-lora/checkpoint-40000
gpt_model: gpt-4

base_model: meta-llama/Meta-Llama-3-8B-Instruct # Update based on preferred base model, e.g. HuggingFaceH4/zephyr-7b-beta 
model_name: llama3 # Update based on model name

condition: cancer # Update based on condition, e.g. stenosis

cancer_definition: Spinal cancer includes malignant lesions that originate from the spine or spinal cord and metastatic or secondary tumours that have spread from another site to the spine.
stenosis_definition: Stenosis is any narrowing or compression of the spinal canal or nerves, including disc protrusions, impingement of nerve roots, or compromise of recesses.
cauda_equina_definition: Cauda equina compression is the compression of a collection of nerve roots called the cauda equina.
herniation_definition: Herniation is a condition in which a disc in the spine ruptures, and the disc nucleus is displaced from intervertebral space.

ivd: False # Set True if extracting labels by IVD level
ivd_level: L3-L4 # Update based on IVD level, e.g. L5-S1